#!/usr/bin/env python3
"""
Split the display face (Smiley Sans / 得意黑, SIL OFL 1.1) into unicode-range
chunks, the same way Google Fonts serves CJK: a page downloads only the
chunks that hold the glyphs it renders (a two-line headline costs a few
small files instead of the 1.1 MB original).

Chunk boundaries reuse Google's frequency-ordered slices for Noto Sans SC
(`font-src/cjk-slices.json`, captured from fonts.googleapis.com), so common
characters cluster together and headlines touch as few chunks as possible.

The output is a Modified Version under the OFL, so it is renamed: the
licence reserves the names "Smiley" and "得意黑" for the original. The family
is served as "GGUU Display".

Usage (needs fontTools + brotli, e.g. `apk add py3-fonttools py3-brotli`):
    python3 scripts/split-display-font.py

Outputs:
    public/fonts/display/display-<n>.woff2 (+ OFL.txt)
    src/app/display-font.css   (imported by globals.css)
"""
import json
import os
import shutil
import sys

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "scripts/font-src/SmileySans-Oblique.ttf.woff2")
SLICES = os.path.join(ROOT, "scripts/font-src/cjk-slices.json")
OUT_DIR = os.path.join(ROOT, "public/fonts/display")
LICENSE = os.path.join(ROOT, "scripts/font-src/OFL.txt")
CSS_OUT = os.path.join(ROOT, "src/app/display-font.css")
FAMILY = "GGUU Display"
TMP_TTF = "/tmp/split-display-font-source.ttf"


def compact_ranges(codepoints):
    """[0x41, 0x42, 0x43, 0x50] -> 'U+41-43, U+50'"""
    out = []
    start = prev = None
    for cp in sorted(codepoints):
        if start is None:
            start = prev = cp
        elif cp == prev + 1:
            prev = cp
        else:
            out.append((start, prev))
            start = prev = cp
    if start is not None:
        out.append((start, prev))
    return ", ".join(f"U+{a:x}" if a == b else f"U+{a:x}-{b:x}" for a, b in out)


def rename(font):
    """Drop the Reserved Font Name from the subset's name table (OFL clause 3)."""
    for record in font["name"].names:
        if record.nameID in (1, 16):
            record.string = FAMILY
        elif record.nameID in (3, 4):
            record.string = f"{FAMILY} Regular"
        elif record.nameID == 6:
            record.string = FAMILY.replace(" ", "") + "-Regular"
        elif record.nameID == 17:
            record.string = "Regular"


def main():
    # Decompress once; subsetting from a plain TTF is much faster.
    source = TTFont(SRC)
    source.flavor = None
    source.save(TMP_TTF)
    font = TTFont(TMP_TTF)
    available = set(font.getBestCmap().keys())
    slices = json.load(open(SLICES))

    if os.path.isdir(OUT_DIR):
        shutil.rmtree(OUT_DIR)
    os.makedirs(OUT_DIR)
    shutil.copy(LICENSE, os.path.join(OUT_DIR, "OFL.txt"))

    seen = set()
    faces = []
    total = 0
    for index, ranges in enumerate(slices):
        wanted = set()
        for a, b in ranges:
            wanted.update(range(a, b + 1))
        codepoints = (wanted & available) - seen
        if not codepoints:
            continue
        seen |= codepoints
        options = subset.Options()
        options.flavor = "woff2"
        options.layout_features = ["*"]
        options.name_IDs = ["*"]
        options.notdef_outline = True
        subsetter = subset.Subsetter(options)
        chunk = TTFont(TMP_TTF)
        subsetter.populate(unicodes=codepoints)
        subsetter.subset(chunk)
        rename(chunk)
        name = f"display-{len(faces)}.woff2"
        path = os.path.join(OUT_DIR, name)
        chunk.flavor = "woff2"
        chunk.save(path)
        size = os.path.getsize(path)
        total += size
        faces.append((name, compact_ranges(codepoints)))

    leftover = available - seen
    with open(CSS_OUT, "w") as css:
        css.write(
            "/* Generated by scripts/split-display-font.py. Do not edit by hand.\n"
            " * Derived from Smiley Sans (得意黑) by atelierAnchor, SIL Open Font License 1.1\n"
            " * (see /fonts/display/OFL.txt). Subset and renamed, as the licence requires.\n"
            f" * {len(faces)} chunks, {total // 1024} KB total; a page loads only the chunks it uses. */\n"
        )
        for name, urange in faces:
            css.write(
                "@font-face {\n"
                f'  font-family: "{FAMILY}";\n'
                "  font-style: normal;\n"
                "  font-weight: 400;\n"
                "  font-display: swap;\n"
                f'  src: url("/fonts/display/{name}") format("woff2");\n'
                f"  unicode-range: {urange};\n"
                "}\n"
            )
    print(f"{len(faces)} chunks, {total // 1024} KB, {len(leftover)} glyphs outside the slices", file=sys.stderr)


if __name__ == "__main__":
    main()
